name: Build and Push Docker Image
inputs:
  docker-username:
    required: true
  docker-password:
    required: true
  docker-tag:
    required: true
  environment:
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and push Docker image of onionperf
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ inputs.docker-username }}/onionperf-anon:${{ github.sha }},${{ inputs.docker-username }}/onionperf-anon:${{ inputs.docker-tag }}